#!/usr/bin/env python3
"""Clone complex public repos and run the parser over them, producing a markdown report."""
import os
import shutil
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

# Ensure repo root is on path so `services.parser` and `libs` resolve
REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from libs.utils import get_repo_files, read_file_safe
from services.parser.main import parse_file, build_dependency_graph

REPOS = [
    {"name": "express", "url": "https://github.com/expressjs/express.git", "branch": "master"},
    {"name": "nest", "url": "https://github.com/nestjs/nest.git", "branch": "master"},
    {"name": "langchain", "url": "https://github.com/langchain-ai/langchain.git", "branch": "master"},
]

TMP_DIR = REPO_ROOT / ".tmp-repos"
REPORT_PATH = REPO_ROOT / "complex-repo-parser-results.md"
MAX_FILES_PER_REPO = 1000


def clone(name: str, url: str, branch: str) -> Path:
    dest = TMP_DIR / name
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["git", "clone", "--depth", "1", "--branch", branch, "--single-branch", url, str(dest)]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Failed to clone {name}: {result.stderr}")
    return dest


def parse_repo(repo_path: Path, max_files: int = MAX_FILES_PER_REPO):
    files = get_repo_files(str(repo_path))
    files = files[:max_files]
    parsed = []
    for f in files:
        pf = parse_file(f)
        if pf:
            parsed.append(pf)
    graph = build_dependency_graph(parsed)
    return parsed, graph


def analyze(name: str, parsed: list, graph: dict):
    stats = {
        "name": name,
        "total_files": len(parsed),
        "languages": Counter(f.language for f in parsed),
        "classifications": Counter(f.classification for f in parsed),
        "avg_loc": round(sum(f.lines_of_code for f in parsed) / max(len(parsed), 1), 1),
    }

    # External vs local dependencies
    external_deps = Counter()
    unresolved_local = []
    for f in parsed:
        resolved = set(graph.get(f.path, []))
        resolved_basenames = {Path(r).stem for r in resolved}
        for dep in f.dependencies:
            if dep.startswith(".") or dep.startswith("/"):
                dep_stem = Path(dep).stem
                if dep_stem not in resolved_basenames:
                    unresolved_local.append((f.path, dep))
            else:
                external_deps[dep] += 1

    stats["top_external_deps"] = external_deps.most_common(15)
    stats["graph_edges"] = sum(len(v) for v in graph.values())
    stats["unresolved_local_deps"] = unresolved_local[:20]

    # Anomalies
    anomalies = []
    for f in parsed:
        ast = f.ast_summary
        funcs = ast.get("functions", [])
        classes = ast.get("classes", [])
        if f.language == "typescript" and not funcs and not classes and f.lines_of_code > 20:
            anomalies.append({"path": f.path, "issue": "typescript file with no functions/classes", "language": f.language, "loc": f.lines_of_code})
        if f.language == "unknown":
            anomalies.append({"path": f.path, "issue": "language detected as unknown", "language": f.language, "loc": f.lines_of_code})
        if f.classification in ("middleware", "route", "controller") and not funcs:
            anomalies.append({"path": f.path, "issue": f"classified as {f.classification} but has no functions", "language": f.language, "loc": f.lines_of_code})

    stats["anomalies"] = anomalies[:30]
    return stats


def render_report(all_stats: list) -> str:
    lines = [
        "# Complex Repo Parser Test Results",
        "",
        "This report was generated by running the improved parser over three popular public repositories.",
        "",
    ]
    for s in all_stats:
        lines += [
            f"## {s['name']}",
            "",
            f"- **Files parsed:** {s['total_files']}",
            f"- **Average LOC:** {s['avg_loc']}",
            f"- **Dependency graph edges:** {s['graph_edges']}",
            "",
            "### Languages",
            "",
        ]
        for lang, count in s["languages"].most_common():
            lines.append(f"- {lang}: {count}")
        lines += ["", "### Classifications", ""]
        for cls, count in s["classifications"].most_common():
            lines.append(f"- {cls}: {count}")
        lines += ["", "### Top external dependencies", ""]
        for dep, count in s["top_external_deps"]:
            lines.append(f"- `{dep}`: {count}")
        if s["unresolved_local_deps"]:
            lines += ["", "### Sample unresolved local imports", ""]
            for path, dep in s["unresolved_local_deps"]:
                lines.append(f"- `{path}` → `{dep}`")
        if s["anomalies"]:
            lines += ["", "### Notable anomalies", ""]
            for a in s["anomalies"]:
                lines.append(f"- `{a['path']}` — {a['issue']} (language={a['language']}, loc={a['loc']})")
        lines.append("")
    return "\n".join(lines)


def main():
    if TMP_DIR.exists():
        shutil.rmtree(TMP_DIR)
    TMP_DIR.mkdir(parents=True, exist_ok=True)

    all_stats = []
    for repo in REPOS:
        print(f"\n=== Cloning {repo['name']} ===")
        try:
            repo_path = clone(repo["name"], repo["url"], repo["branch"])
        except RuntimeError as e:
            print(e)
            continue
        print(f"=== Parsing {repo['name']} ===")
        parsed, graph = parse_repo(repo_path)
        print(f"Parsed {len(parsed)} files, {sum(len(v) for v in graph.values())} graph edges")
        stats = analyze(repo["name"], parsed, graph)
        all_stats.append(stats)

    report = render_report(all_stats)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"\nReport written to: {REPORT_PATH}")


if __name__ == "__main__":
    main()
